version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pubmed_integration_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: pubmed
      POSTGRES_PASSWORD: pubmed_password
      POSTGRES_DB: pubmed_integration
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
      - ${PUBMED_DATA_PATH:-./data}:/data:ro
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
        reservations:
          cpus: '2'
          memory: 8G
    command: >
      postgres
        -c shared_buffers=4GB
        -c work_mem=128MB
        -c maintenance_work_mem=1GB
        -c effective_cache_size=12GB
        -c max_worker_processes=16
        -c max_parallel_workers_per_gather=8
        -c random_page_cost=1.1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pubmed -d pubmed_integration"]
      interval: 10s
      timeout: 5s
      retries: 5

  pubmed_processor:
    build:
      context: .
      dockerfile: Dockerfile.processor
    environment:
      DATABASE_URL: postgres://pubmed:pubmed_password@postgres:5432/pubmed_integration
      RUST_LOG: info
      PROCESSING_THREADS: 8
      BATCH_SIZE: 1000
    volumes:
      - ${PUBMED_DATA_PATH:-./data}:/data:ro
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 16G
        reservations:
          cpus: '4'
          memory: 8G
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
